server: 
  port: 8080
# 配置当前服务为客户端
eureka: 
  instance: 
    instance-id: woniucloud-customer-8080 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
  client:
    register-with-eureka: true
    service-url: 
      #服务消费者要连接到的注册中心，集群的三台机器
      defaultZone: http://eurakeserver9000.com:9000/eureka/
spring:
   application:
    name: woniucloud-customert   #当前服务的名字，后面会用到   
    
spring: 
  profiles: customer8080
  
---